import { ADAPTERS, type Adapter, parseTeam } from "./team.ts";

export const BUNDLED_CHARTER_ROLES = new Set(["supervisor", "design", "implementation", "qa"]);

export const DEFAULT_MODELS: Record<Adapter, string> = {
  "claude-code": "claude-opus-4-8",
  codex: "gpt-5.5",
  agy: "gemini-3-pro",
};

export const DEFAULT_ROLES = ["supervisor", "design", "implementation", "qa"] as const;

export interface RoleSpec {
  role: string;
  adapter: Adapter;
  model: string;
}

export interface InitSpec {
  roles: RoleSpec[];
  comments: boolean;
}

export class InitError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InitError";
  }
}

function validateRoleSpecs(roles: RoleSpec[]): void {
  for (const r of roles) {
    if (!(ADAPTERS as readonly string[]).includes(r.adapter)) {
      throw new InitError(
        `unknown adapter "${r.adapter}" for role "${r.role}". Valid: ${ADAPTERS.join(", ")}`,
      );
    }
    if (!r.model.trim()) {
      throw new InitError(`model for role "${r.role}" must not be empty`);
    }
  }
}

/** Supervisor first, then others in original order. */
function orderRoles(roles: RoleSpec[]): RoleSpec[] {
  const sup = roles.find((r) => r.role === "supervisor");
  const others = roles.filter((r) => r.role !== "supervisor");
  return sup ? [sup, ...others] : [...roles];
}

export function buildTeamYaml(spec: InitSpec): string {
  validateRoleSpecs(spec.roles);
  const ordered = orderRoles(spec.roles);

  const lines: string[] = [];

  if (spec.comments) {
    lines.push("# Generated by agvsr init. Edit freely or regenerate with --force.");
    lines.push("# `model` is a raw per-CLI model string; team.yaml is the source of truth.");
    lines.push("# Omit `charter` to use the bundled default; `charter_append` adds project rules;");
    lines.push("# `charter` replaces it wholesale.");
  }

  lines.push("roles:");
  for (const r of ordered) {
    if (spec.comments && !BUNDLED_CHARTER_ROLES.has(r.role)) {
      lines.push(
        `  # TODO: add charter or charter_append for role "${r.role}" (no bundled charter)`,
      );
    }
    lines.push(`  ${r.role}:`);
    lines.push(`    adapter: ${r.adapter}`);
    lines.push(`    model: ${r.model}`);
  }

  if (spec.comments) {
    lines.push("");
    lines.push("# Optional event hooks. Each value is a shell command run via `sh -c`.");
    lines.push("# The event JSON object is written to the command's stdin.");
    lines.push("# All keys are optional — omit any you don't need.");
    lines.push("# hooks:");
    lines.push("#   on_job_done: \"notify-send 'agvsr' 'Job complete'\"");
    lines.push("#   on_job_failed: \"notify-send 'agvsr' 'Job failed'\"");
    lines.push(
      '#   on_supervisor_message: "osascript -e \'display notification \\"Supervisor needs input\\" with title \\"agvsr\\"\'"',
    );
  }

  const output = lines.join("\n") + "\n";

  // Self-check: generated YAML must pass parseTeam (catches missing supervisor, bad adapter, etc.)
  parseTeam(output);

  return output;
}

export function buildTeamToml(spec: InitSpec): string {
  validateRoleSpecs(spec.roles);
  const ordered = orderRoles(spec.roles);

  const lines: string[] = [];

  if (spec.comments) {
    lines.push("# Generated by agvsr init. Edit freely or regenerate with --force.");
    lines.push("# `model` is a raw per-CLI model string; team.toml is the source of truth.");
    lines.push("# Omit `charter` to use the bundled default; `charter_append` adds project rules;");
    lines.push("# `charter` replaces it wholesale.");
  }

  ordered.forEach((r, i) => {
    if (i > 0 || spec.comments) lines.push("");
    if (spec.comments && !BUNDLED_CHARTER_ROLES.has(r.role)) {
      lines.push(`# TODO: add charter or charter_append for role "${r.role}" (no bundled charter)`);
    }
    lines.push(`[roles.${r.role}]`);
    lines.push(`adapter = "${r.adapter}"`);
    lines.push(`model = "${r.model}"`);
  });

  if (spec.comments) {
    lines.push("");
    lines.push("# Optional event hooks. Each value is a shell command run via `sh -c`.");
    lines.push("# The event JSON object is written to the command's stdin.");
    lines.push("# All keys are optional — omit any you don't need.");
    lines.push("# [hooks]");
    lines.push("# on_job_done = \"notify-send 'agvsr' 'Job complete'\"");
    lines.push("# on_job_failed = \"notify-send 'agvsr' 'Job failed'\"");
    lines.push(
      '# on_supervisor_message = "osascript -e \'display notification \\"Supervisor needs input\\" with title \\"agvsr\\"\'"',
    );
  }

  const output = lines.join("\n") + "\n";

  // Self-check: generated TOML must pass parseTeam (catches missing supervisor, bad adapter, etc.)
  parseTeam(output, "toml");

  return output;
}

export function resolveRoleSpecs(options: {
  roleNames: string[];
  defaultAdapter: Adapter;
  defaultModel?: string;
  roleOverrides: Map<string, { adapter?: Adapter; model?: string }>;
}): RoleSpec[] {
  return options.roleNames.map((role) => {
    const ov = options.roleOverrides.get(role);
    const adapter = ov?.adapter ?? options.defaultAdapter;
    const model = ov?.model ?? options.defaultModel ?? DEFAULT_MODELS[adapter];
    return { role, adapter, model };
  });
}
